version: 2

project_name: miosa

before:
  hooks:
    - go mod tidy

builds:
  - id: miosa
    main: ./cmd/miosa
    binary: miosa
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/Miosa-osa/miosa-cli-go/commands.cliVersion={{.Version}}'

archives:
  - id: miosa
    ids:
      - miosa
    name_template: "miosa_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"
