package commands

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// Hidden maintenance commands that generate the reference docs from the real
// command tree, so the docs cannot drift from the code:
//
//	miosa __docs     > docs/commands.md
//	miosa __api-map  > docs/api-map.md

func init() {
	rootCmd.AddCommand(
		&cobra.Command{
			Use: "__docs", Hidden: true, Short: "Print the command reference as Markdown", Args: cobra.NoArgs,
			RunE: func(cmd *cobra.Command, _ []string) error { return WriteCommandReference(cmd.OutOrStdout()) },
		},
		&cobra.Command{
			Use: "__api-map", Hidden: true, Short: "Print which API route each command calls", Args: cobra.NoArgs,
			RunE: func(cmd *cobra.Command, _ []string) error { return WriteAPIMap(cmd.OutOrStdout()) },
		},
	)
}

// WriteCommandReference writes every visible command with its usage, long
// description, flags and aliases, one sentence per line.
func WriteCommandReference(w io.Writer) error {
	finalize()
	fmt.Fprintln(w, "# miosa command reference")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Generated by `miosa __docs`; do not edit by hand.")
	fmt.Fprintln(w, "Regenerate with `make docs`.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "## Global flags")
	fmt.Fprintln(w)
	writeFlags(w, rootCmd.PersistentFlags())
	fmt.Fprintln(w)
	top := visible(rootCmd.Commands())
	fmt.Fprintln(w, "## Commands")
	fmt.Fprintln(w)
	for _, c := range top {
		fmt.Fprintf(w, "- [`miosa %s`](#%s) - %s\n", c.Name(), anchor("miosa "+c.Name()), c.Short)
	}
	fmt.Fprintln(w)
	for _, c := range top {
		writeCommand(w, c, 2)
	}
	return nil
}

func visible(cmds []*cobra.Command) []*cobra.Command {
	out := make([]*cobra.Command, 0, len(cmds))
	for _, c := range cmds {
		if c.Hidden || c.Deprecated != "" || c.Name() == "help" || c.Name() == "completion" {
			continue
		}
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

func anchor(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-':
			b.WriteRune(r)
		case r == ' ':
			b.WriteRune('-')
		}
	}
	return b.String()
}

func writeCommand(w io.Writer, c *cobra.Command, level int) {
	path := strings.TrimPrefix(c.CommandPath(), "")
	fmt.Fprintf(w, "%s `%s`\n\n", strings.Repeat("#", level+1), path)
	if c.Short != "" {
		fmt.Fprintf(w, "%s\n\n", ensureSentence(c.Short))
	}
	fmt.Fprintf(w, "```\n%s\n```\n\n", c.UseLine())
	if long := strings.TrimSpace(c.Long); long != "" && long != c.Short {
		fmt.Fprintf(w, "%s\n\n", oneSentencePerLine(long))
	}
	if len(c.Aliases) > 0 {
		fmt.Fprintf(w, "Aliases: %s.\n\n", "`"+strings.Join(c.Aliases, "`, `")+"`")
	}
	if c.HasLocalFlags() {
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w)
		writeFlags(w, c.LocalNonPersistentFlags())
		fmt.Fprintln(w)
	}
	if strings.TrimSpace(c.Example) != "" {
		fmt.Fprintf(w, "Examples:\n\n```\n%s\n```\n\n", strings.TrimSpace(c.Example))
	}
	subs := visible(c.Commands())
	if len(subs) > 0 && level < 5 {
		for _, s := range subs {
			writeCommand(w, s, level+1)
		}
	}
}

func writeFlags(w io.Writer, fs *pflag.FlagSet) {
	var names []string
	byName := map[string]*pflag.Flag{}
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		names = append(names, f.Name)
		byName[f.Name] = f
	})
	sort.Strings(names)
	for _, n := range names {
		f := byName[n]
		flag := "--" + f.Name
		if f.Shorthand != "" {
			flag = "-" + f.Shorthand + ", " + flag
		}
		def := ""
		if f.DefValue != "" && f.DefValue != "false" && f.DefValue != "0" && f.DefValue != "[]" {
			def = fmt.Sprintf(" (default `%s`)", f.DefValue)
		}
		typ := f.Value.Type()
		if typ == "bool" {
			typ = ""
		} else {
			typ = " " + typ
		}
		fmt.Fprintf(w, "- `%s%s` - %s%s\n", flag, typ, ensureSentence(f.Usage), def)
	}
}

func ensureSentence(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return s
	}
	if !strings.HasSuffix(s, ".") && !strings.HasSuffix(s, ":") && !strings.HasSuffix(s, "?") {
		s += "."
	}
	return s
}

// oneSentencePerLine puts each sentence of prose on its own line, leaving
// indented examples and lists untouched.
func oneSentencePerLine(long string) string {
	var out []string
	inCode := false
	for _, line := range strings.Split(long, "\n") {
		trimmed := strings.TrimSpace(line)
		isExample := strings.HasPrefix(line, "  ") || strings.HasPrefix(line, "\t")
		if isExample && !inCode {
			out = append(out, "```", strings.TrimRight(line, " "))
			inCode = true
			continue
		}
		if inCode && (isExample || trimmed == "") {
			out = append(out, strings.TrimRight(line, " "))
			continue
		}
		if inCode {
			out = append(out, "```")
			inCode = false
		}
		out = append(out, splitSentences(line))
	}
	if inCode {
		out = append(out, "```")
	}
	return strings.TrimSpace(strings.Join(out, "\n"))
}

func splitSentences(line string) string {
	var b strings.Builder
	runes := []rune(line)
	for i, r := range runes {
		b.WriteRune(r)
		if (r == '.' || r == '?' || r == '!') && i+1 < len(runes) && runes[i+1] == ' ' && i+2 < len(runes) && runes[i+2] >= 'A' && runes[i+2] <= 'Z' {
			b.WriteRune('\n')
			// skip the single space
			runes[i+1] = 0
		}
	}
	return strings.ReplaceAll(b.String(), "\x00", "")
}

// WriteAPIMap lists the API route behind every declarative command, read from
// the command tree. Commands with bespoke logic (login, files, console,
// prompt, ...) call several routes and are described in their own help.
func WriteAPIMap(w io.Writer) error {
	finalize()
	type row struct{ cmd, method, path string }
	var rows []row
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		if r, ok := c.Annotations[routeAnnotation]; ok && !c.Hidden {
			method, path, _ := strings.Cut(r, " ")
			rows = append(rows, row{c.CommandPath(), method, path})
		}
		for _, s := range c.Commands() {
			walk(s)
		}
	}
	walk(rootCmd)
	sort.Slice(rows, func(i, j int) bool { return rows[i].cmd < rows[j].cmd })
	fmt.Fprintln(w, "# API route behind each command")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Generated by `miosa __api-map`; do not edit by hand.")
	fmt.Fprintln(w, "Only declarative commands are listed.")
	fmt.Fprintln(w, "Paths are relative to the API base URL (`/api/v1`); `{N}` is the Nth argument.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Command | Method | Route |")
	fmt.Fprintln(w, "|---|---|---|")
	for _, r := range rows {
		fmt.Fprintf(w, "| `%s` | %s | `%s` |\n", r.cmd, r.method, r.path)
	}
	return nil
}
